app.py
from flask import Flask
from views import my_view

app = Flask(__name__)
app.register_blueprint(my_view)

if __name__ == "__main__":
    app.run(debug=True, port=8000)

views.py
from flask import render_template, Blueprint, request
from fav_bands import favourite_bands

my_view = Blueprint("my_view", __name__)

class BandEntry():
    def __init__(self, song_name, song_album, song_artist, song_rating):
        self.song = song_name
        self.album = song_album
        self.artist = song_artist
        self.rating = song_rating

bands=[]

@my_view.route("/")
def index():
    return render_template("index.html")

@my_view.route("/page2")
def page2():
    return render_template("page2.html", bands= bands)

@my_view.route("/page3", methods=["GET", "POST"])
def page3():
    if request.method == "POST":
        new_band = BandEntry(
            request.form["added_song"],
            request.form["added_album"],
            request.form["added_artist"],
            int(request.form["added_rating"]))
        bands.append(new_band)
    return render_template("page3.html")

        

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zoltan First Flask App</title>
    <link 
    rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" 
    href="{{ url_for('static', filename='style.css')}}">
</head>
<body>
    <h2>HTML Forms</h2>
    <nav>
        <a href="{{ url_for('my_view.index')}}">Home</a>
        <a href="{{ url_for('my_view.page2')}}">Page 2</a>
        <a href="{{ url_for('my_view.page3')}}">Page 3</a>
        </nav>
        


    {% block content %}

    {% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur iste nihil, ratione quibusdam aperiam necessitatibus quod non itaque iusto, mollitia molestias enim eligendi unde impedit veritatis odio officiis vero corrupti ex assumenda aliquam consequuntur? Qui saepe inventore amet soluta consectetur dolores nulla dicta id? Praesentium eum, officiis similique iusto omnis reiciendis non alias temporibus perferendis. Vero consectetur a alias quod eum dolorem qui, minima nesciunt beatae, perspiciatis sequi. Sit iste fugiat quod fugit odio repudiandae quam officiis alias vel nesciunt, provident doloribus iusto! Sapiente laborum, accusantium id velit omnis fugit facere quae aperiam adipisci nihil deleniti explicabo quibusdam ipsa aspernatur magni sequi autem ipsam praesentium debitis dignissimos dicta repudiandae nemo! Corporis doloremque corrupti adipisci repudiandae vero consequuntur aliquam fuga unde soluta sint at ratione cum recusandae nesciunt asperiores vel, praesentium nisi, magni voluptates id distinctio voluptate. Ea quisquam atque assumenda cumque placeat incidunt nemo nostrum repudiandae dicta repellendus quis iure iste dolor dolorum numquam soluta, enim, omnis provident fugiat libero corrupti officia cum adipisci! Amet ad repellat beatae sequi vero id, officiis, ab iste voluptas aliquid quia ea itaque? Repellat saepe totam aliquam deleniti! Molestias eos a quod eum odit! Ipsa corrupti hic saepe eaque quaerat sunt, voluptates ad recusandae..</p>

{% endblock %}

templates/page2.html
{% extends 'base.html' %} {% block content %}

<p>This is my second page of my app! </p>

{#My ratings:#} 

{% for band in bands %}
<div>{{ band.song }}, {{ band.album }}, {{ band.artist }}, {{ band.rating }}
    {% for i in range(band.rating) %}
    *
    {% endfor %}
</div>
{% endfor %} {% endblock %}

templates/page3.html
{% extends 'base.html' %}

{% block content %}
    <p>Hello! This is a test page</p>
   <form action="/my_name" method="post">
        <input type="text" name="added_song"  placeholder="Enter a song" required>
        <input type="text" name="added_album"  placeholder="Add the album" required>
        <input type="text" name="added_artist"  placeholder="Add the artist" required>
        <select name="added_rating">
            <option value="1">1 *</option>
            <option value="2">2 **</option>
            <option value="3">3 ***</option>
            <option value="4">4 ****</option>
            <option value="5">5 *****</option>
        </select>
        <button type="submit">Submit</button>

    </form>

{% endblock %}